export const DUMMY_PROJECTS = [
  {
    id: 1,
    title: "Food App",
    description: "It's a basic food app created by useContext Hook.",
    img: "../../images/FoodApp.jpg",
    website: "https://charming-sfogliatella-ca0c14.netlify.app/",
  },
  {
    id: 2,
    title: "Omnifood",
    description: "Omnifood - Food delivery app, created by HTML and CSS.",
    img: "../../images/OmniFood.jpg",
    website: "https://secondomnifood.netlify.app/",
  },
  {
    id: 3,
    title: "Resume Generator",
    description: "It's a Resume Generator, which is created by React.",
    img: "../../images/ResumeGenerator.jpg",
    website: "https://magenta-chaja-dea9f2.netlify.app/",
  },
  {
    id: 4,
    title: "Calculator",
    description: "It's a simple Calculator, which is created by React.",
    img: "../../images/calc.jpg",
    website: "https://peppy-elf-90bed5.netlify.app/",
  },
  {
    id: 5,
    title: "Star Wars Characters",
    description: "Star War list, with some info in it. Created by React.",
    img: "../../images/starwars.jpg",
    website: "https://idyllic-babka-fcecac.netlify.app/",
  },
  {
    id: 6,
    title: "E-commerce",
    description: "Simple e-commerce app",
    img: "../../images/e-commerce.jpg",
    website: "https://lucky-smakager-74b0e2.netlify.app/",
  },
  {
    id: 7,
    title: "Infinite Scrolling",
    description: "Implemented infinite scrolling by React",
    img: "../../images/infinite-scroll.png",
    website: "https://github.com/Makata1962/Sweeft-Infinite-Scroll",
  },

  {
    id: 8,
    title: "Monsters Rolodex",
    description: "Monsters Rolodex App",
    img: "../../images/monsters-rolodex.jpg",
    website: "https://harmonious-melba-60c738.netlify.app/",
  },
  {
    id: 9,
    title: "Landing Page with SCSS",
    description: "Landing Page created by HTML & SCSS to master SCSS",
    img: "../../images/webpage-scss.jpg",
    website: "https://imaginative-madeleine-007077.netlify.app/",
  },
  {
    id: 10,
    title: "Random Company's webpage",
    description: "Landing Page created by HTML & CSS",
    img: "../../images/webpage-css.jpg",
    website: "https://stirring-dasik-8892a8.netlify.app/",
  },
];
